- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          