---
- name: Server install
  hosts: all
  remote_user: root
  tasks:
  - name: "User | Create user"
    user:
      name: "{{ user }}"
      shell: /bin/bash
  - name: User | SSH key
    authorized_key: 
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
